[package]
name = "emulate"
description = "Performing a guest's instruction on its behalf, where the hardware must not"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
iced-x86 = { workspace = true }
log = { workspace = true }
memory = { workspace = true }
npt = { workspace = true }
paging = { workspace = true }
processor = { workspace = true }
svm = { workspace = true }
thiserror = { workspace = true }
vcpu = { workspace = true }
x86_64 = { workspace = true }

[lints]
workspace = true
